# Generated by Django 5.1.7 on 2025-03-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_code_product_buying_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='buying Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='DEFAULT_SKU', help_text='Unique stock keeping unit identifier', max_length=50, unique=True, verbose_name='Product SKU'),
        ),
    ]
