# Generated by Django 5.1.7 on 2025-03-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.CharField(blank=True, help_text='Comma separated list (e.g., Red,Blue,Green)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Comma separated list (e.g., S,M,L,XL)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='mandatory_fields',
            field=models.CharField(choices=[('none', 'None'), ('size', 'Size'), ('color', 'Color'), ('both', 'Both')], default='none', max_length=10),
        ),
    ]
