# Generated by Django 5.1.7 on 2025-04-02 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_coupon_remove_cartitem_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('order_channel', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('cod', 'Cash on Delivery')], max_length=50)),
                ('bikash_trxid', models.CharField(blank=True, max_length=255, null=True)),
                ('nagad_trxid', models.CharField(blank=True, max_length=255, null=True)),
                ('last_four_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
