# Generated by Django 5.1.7 on 2025-04-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_coupon_minimum_purchase_order_coupon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bikash_trxid',
            new_name='bkash_trxid',
        ),
    ]
