# Generated by Django 5.1.7 on 2025-04-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
            ],
            options={
                'verbose_name': 'Sales Report',
                'verbose_name_plural': 'Sales Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.orderitem',),
        ),
    ]
